/**
 * Console sessions — the thing HTTP Basic could never give us: an identity that can be
 * ended.
 *
 * Built against OWASP's Session Management Cheat Sheet (read 2026-08-21), which is quoted
 * where it decided something:
 *
 *   - "Session identifiers must have at least 64 bits of entropy". This uses 256 —
 *     `randomBytes(32)`, base64url. There is no reason to be near a floor that cheap.
 *   - "The session ID must be renewed or regenerated by the web application after any
 *     privilege level change". Signing in mints a new token; changing a password mints a
 *     new one and destroys every other session for that account.
 *   - Idle timeout AND absolute timeout, not one of them. An idle-only session lives
 *     forever if a tab is left open; an absolute-only one keeps an abandoned laptop signed
 *     in all day.
 *   - "the web application must take active actions to invalidate the session on both
 *     sides, client and server". Logout deletes the server record — clearing the cookie
 *     alone would leave a token that still works if it was ever copied.
 *
 * The token is stored as its SHA-256, never in the clear. Same reasoning as the password
 * hash one file over: someone who reads `console.json` gets a list of dead hashes, not a
 * set of live sessions. A session token is a bearer credential; treating it as less than
 * one because it is short-lived is how session files become the soft target.
 *
 * NOT DONE, deliberately: rotating the token on a timer the way Grafana does
 * (`token_rotation_interval_minutes`, default 10). Rotation needs a grace window, because
 * this console holds an SSE stream open and fires parallel asset + API requests — a
 * rotation mid-page swaps the cookie under requests already in flight and signs the
 * operator out at random. Grafana carries that grace window; we would have to build one,
 * and the idle + absolute pair already bounds a stolen token. Written down so the next
 * session knows it was a decision, not an oversight.
 */
import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import type { ConsoleSession, ConsoleStore, ConsoleUser } from "./console-store.ts";

/** 256 bits. OWASP's floor is 64. */
const TOKEN_BYTES = 32;

export interface SessionLifetimes {
  /**
   * Idle window. OWASP suggests 15-30 min for low-risk applications and 2-5 for
   * high-value ones; Grafana, the closest comparable product, ships SEVEN DAYS
   * (`login_maximum_inactive_lifetime_duration`). Eight hours sits between them on
   * purpose: this console is an ops surface someone keeps open through a working day,
   * and a 30-minute idle timeout on a self-hosted box gets solved by the operator
   * disabling authentication entirely, which is a worse outcome than the one it prevents.
   */
  idleMs: number;
  /**
   * Hard ceiling regardless of activity. Grafana's equivalent is 30 days; seven is the
   * stricter end, and it is the number that bounds a token stolen from a browser profile.
   */
  absoluteMs: number;
}

export const DEFAULT_LIFETIMES: SessionLifetimes = {
  idleMs: 8 * 60 * 60 * 1000,
  absoluteMs: 7 * 24 * 60 * 60 * 1000,
};

/**
 * `lastSeenAt` is persisted only when it has moved by more than this. Without a floor,
 * every request rewrites the state file — a page load is twenty writes, and an open SSE
 * stream turns an idle console into a disk-writing loop. A minute of imprecision on an
 * eight-hour idle window is not a security property anyone can name.
 */
const TOUCH_FLOOR_MS = 60_000;

/**
 * ...but never more than half the idle window. A flat floor is a silent trap: with
 * `CONSOLE_SESSION_IDLE_MINUTES=1` the anchor would never be refreshed before the session
 * had already expired, so an actively-used console would sign the operator out every
 * minute and the logs would show a perfectly healthy session store. Measured while writing
 * the absolute-timeout test, which failed for exactly this reason.
 */
const touchFloorFor = (idleMs: number): number => Math.min(TOUCH_FLOOR_MS, Math.floor(idleMs / 2));

export const hashToken = (token: string): string => createHash("sha256").update(token).digest("hex");

/** Constant-time compare of two hex digests — the lookup below must not leak by timing. */
function sameDigest(a: string, b: string): boolean {
  const ab = Buffer.from(a, "hex");
  const bb = Buffer.from(b, "hex");
  if (ab.length !== bb.length || ab.length === 0) return false;
  return timingSafeEqual(ab, bb);
}

export interface IssuedSession {
  /** Give this to the browser once. It is never recoverable from the store afterwards. */
  token: string;
  session: ConsoleSession;
}

export interface SessionContext {
  ip?: string;
  userAgent?: string;
  now?: () => Date;
}

export async function createSession(
  store: ConsoleStore,
  userId: string,
  ctx: SessionContext = {},
  lifetimes: SessionLifetimes = DEFAULT_LIFETIMES,
): Promise<IssuedSession> {
  const token = randomBytes(TOKEN_BYTES).toString("base64url");
  const stamp = (ctx.now?.() ?? new Date()).toISOString();
  const session: ConsoleSession = {
    tokenHash: hashToken(token),
    userId,
    createdAt: stamp,
    lastSeenAt: stamp,
    ...(ctx.ip ? { ip: ctx.ip } : {}),
    // Truncated: it is attacker-controlled and only ever displayed back to the operator.
    ...(ctx.userAgent ? { userAgent: ctx.userAgent.slice(0, 200) } : {}),
  };
  await store.update((draft) => {
    // Sweep here, and only here. Sessions were previously removed only when a token was
    // presented again after expiry, on logout, or on disable — so a browser closed without
    // signing out left its row forever. Measured 2026-08-21: six sign-ins, six rows, none
    // reclaimed. That is the "why is this file 40 MB" bug this store's own comment says it
    // was avoiding, and every request pays for it, because `read()` clones the array.
    //
    // Creation is the right moment: it is exactly when the array grows, it is already
    // under the lock, and it costs no extra write.
    const at = (ctx.now?.() ?? new Date()).getTime();
    draft.sessions = draft.sessions.filter(
      (s) => at < Date.parse(s.lastSeenAt) + lifetimes.idleMs && at < Date.parse(s.createdAt) + lifetimes.absoluteMs,
    );
    draft.sessions.push(session);
  });
  return { token, session };
}

export interface ResolvedSession {
  user: ConsoleUser;
  session: ConsoleSession;
}

export type SessionRejection = "absent" | "unknown" | "expired" | "disabled";

export type SessionLookup = { ok: true; value: ResolvedSession } | { ok: false; reason: SessionRejection };

/**
 * Resolve a presented token, enforcing both lifetimes and refreshing the idle anchor.
 *
 * An expired or unknown session is DELETED here rather than left to a sweep: the store is
 * small, the cost is one write, and a session file that accumulates dead rows is how a
 * "why is this file 40 MB" bug arrives a year later.
 */
export async function resolveSession(
  store: ConsoleStore,
  token: string | undefined,
  lifetimes: SessionLifetimes = DEFAULT_LIFETIMES,
  now: () => Date = () => new Date(),
): Promise<SessionLookup> {
  if (!token) return { ok: false, reason: "absent" };
  const digest = hashToken(token);
  const state = await store.read();
  const session = state.sessions.find((s) => sameDigest(s.tokenHash, digest));
  if (!session) return { ok: false, reason: "unknown" };

  const at = now().getTime();
  const idleDeadline = Date.parse(session.lastSeenAt) + lifetimes.idleMs;
  const absoluteDeadline = Date.parse(session.createdAt) + lifetimes.absoluteMs;
  if (!(at < idleDeadline && at < absoluteDeadline)) {
    await destroySession(store, token);
    return { ok: false, reason: "expired" };
  }

  const user = state.users.find((u) => u.id === session.userId);
  if (!user || user.disabledAt) {
    await destroySession(store, token);
    return { ok: false, reason: "disabled" };
  }

  if (at - Date.parse(session.lastSeenAt) > touchFloorFor(lifetimes.idleMs)) {
    const stamp = new Date(at).toISOString();
    await store.update((draft) => {
      const live = draft.sessions.find((s) => s.tokenHash === digest);
      if (live) live.lastSeenAt = stamp;
    });
  }

  return { ok: true, value: { user, session } };
}

export async function destroySession(store: ConsoleStore, token: string): Promise<void> {
  const digest = hashToken(token);
  await store.update((draft) => {
    draft.sessions = draft.sessions.filter((s) => s.tokenHash !== digest);
  });
}

/** Every session for one account. Used on a password change and on disable. */
export async function destroyUserSessions(store: ConsoleStore, userId: string, keepToken?: string): Promise<void> {
  const keep = keepToken ? hashToken(keepToken) : null;
  await store.update((draft) => {
    draft.sessions = draft.sessions.filter((s) => s.userId !== userId || s.tokenHash === keep);
  });
}

/**
 * The cookie name, chosen per request.
 *
 * `__Host-` is what OWASP asks for and what stops a network attacker (or a sibling
 * subdomain) overwriting the cookie — but the prefix REQUIRES the `Secure` attribute, and
 * a Secure cookie is not accepted by every browser over plain http, including
 * `http://127.0.0.1`. Hard-coding the prefix would make the console unusable in exactly
 * its most common deployment: loopback, no TLS, behind an SSH tunnel.
 *
 * So the prefix and `Secure` are used together whenever the request is actually secure,
 * and dropped together when it is not. There is no configuration knob for this: an
 * operator cannot be expected to know that a cookie name has security semantics.
 */
export const SESSION_COOKIE_BASE = "naulon_console";
export const cookieNameFor = (secure: boolean): string =>
  secure ? `__Host-${SESSION_COOKIE_BASE}` : SESSION_COOKIE_BASE;

/** Both names, so a cookie set before/after a TLS change is still found and can be cleared. */
export const SESSION_COOKIE_NAMES: readonly string[] = [`__Host-${SESSION_COOKIE_BASE}`, SESSION_COOKIE_BASE];

export interface CookieOptions {
  secure: boolean;
  /** Session cookie (no Max-Age) unless given — the absolute lifetime is enforced server-side regardless. */
  maxAgeSeconds?: number;
}

export function sessionCookie(token: string, opts: CookieOptions): string {
  const parts = [
    `${cookieNameFor(opts.secure)}=${token}`,
    "Path=/",
    "HttpOnly",
    // Strict, not Lax: nothing links INTO this console from another site, so the usual
    // "Lax keeps top-level navigation working" argument buys nothing and Strict removes
    // the whole cross-site request class.
    "SameSite=Strict",
  ];
  if (opts.secure) parts.push("Secure");
  // Deliberately no Domain: `__Host-` forbids it, and without the prefix it would still be
  // widening the cookie to every sibling subdomain for no gain.
  if (opts.maxAgeSeconds !== undefined) parts.push(`Max-Age=${Math.floor(opts.maxAgeSeconds)}`);
  return parts.join("; ");
}

/** Expire both spellings — the browser may hold whichever one it was given. */
export function clearSessionCookies(secure: boolean): string[] {
  return SESSION_COOKIE_NAMES.map((name) => {
    const parts = [`${name}=`, "Path=/", "HttpOnly", "SameSite=Strict", "Max-Age=0"];
    // `__Host-` cookies are only deletable with Secure set; sending it on a plain-http
    // response is harmless (the browser has no such cookie to begin with).
    if (secure || name.startsWith("__Host-")) parts.push("Secure");
    return parts.join("; ");
  });
}

/**
 * Read the token out of a Cookie header. Written by hand rather than pulled from
 * `hono/cookie` because both spellings have to be tried and the result must not depend on
 * cookie ordering; the parse is six lines and the dependency surface stays four packages.
 */
export function tokenFromCookieHeader(header: string | undefined): string | undefined {
  if (!header) return undefined;
  const jar = new Map<string, string>();
  for (const part of header.split(";")) {
    const eq = part.indexOf("=");
    if (eq < 1) continue;
    jar.set(part.slice(0, eq).trim(), part.slice(eq + 1).trim());
  }
  for (const name of SESSION_COOKIE_NAMES) {
    const value = jar.get(name);
    if (value) return value;
  }
  return undefined;
}

/**
 * Is this request on a secure origin? `X-Forwarded-Proto` is honoured because the
 * documented deployment for this console is exactly "Caddy on :443 → 127.0.0.1", where
 * the socket is plain http and the browser's origin is https.
 *
 * The header is attacker-controlled on a directly-exposed console, and the consequence of
 * believing a forged one is a Secure+`__Host-` cookie the browser then refuses to send
 * back over http — a self-inflicted sign-in failure, not a downgrade. Believing the
 * opposite (ignoring a real proxy) would drop the prefix on a genuinely https console,
 * which IS a downgrade. Trusting it is the safe direction.
 */
export function isSecureRequest(url: string, forwardedProto: string | undefined): boolean {
  const proto = forwardedProto?.split(",")[0]?.trim().toLowerCase();
  if (proto) return proto === "https";
  try {
    return new URL(url).protocol === "https:";
  } catch {
    return false;
  }
}
