/**
 * `naulon init` — the pure, testable core.
 *
 * A self-hoster's setup cliff today is: copy a 180-line `.env.example`, hand-edit it,
 * AND hand-author a credits source that satisfies the contract. `init` collapses that
 * into a short prompt flow. This module is the part with no I/O and no prompts: it turns
 * validated answers into the exact bytes of the two files the gate boots from — so it can
 * be unit-tested with fixtures, never touching a TTY or the filesystem (the same split as
 * `runCheck` vs the `check` CLI shell).
 *
 * Every generated `credits.json` entry is run through the real `creditsSchema` before it
 * is returned, so `init` can never emit a file the gate would reject at boot.
 */
import { z } from "zod";
import { walletSchema, walletAddress } from "../contract/wallet.ts";
import { parseCredits, type ArticleCredits } from "../contract/credits.ts";

/** A clearly-fake but structurally-valid address, so a wallet-less starter still boots. */
export const PLACEHOLDER_WALLET = "0x0000000000000000000000000000000000000000";

/**
 * The answers the wizard resolves (from flags, prompts, or defaults) before planning.
 * Mirrors the env surface the gate actually reads (`shared/src/config.ts`) — the real
 * public contract a self-hoster pins to.
 */
export const initAnswersSchema = z
  .object({
    originUrl: z.string().url(),
    priceUsdc: z.number().positive(),
    citationMultiplier: z.number().positive(),
    paymentMode: z.enum(["mock", "gateway"]),
    settlementNetwork: z.enum(["arcTestnet", "baseSepolia", "base"]).default("arcTestnet"),
    tollgatePort: z.number().int().positive(),
    articlePrefixes: z.string().min(1),
    /** Where the starter credits map is written; also becomes CREDITS_FIXTURES. */
    creditsPath: z.string().min(1),
    /** The starter article + its author. Wallet-less → a placeholder + a loud warning. */
    starterSlug: z.string().min(1),
    starterTitle: z.string().min(1),
    starterAuthorId: z.string().min(1),
    defaultWallet: walletSchema.optional(),
  })
  .strict();

export type InitAnswers = z.infer<typeof initAnswersSchema>;

/** Schema-level defaults, surfaced to the CLI so prompts can show them in brackets. */
export const INIT_DEFAULTS = {
  originUrl: "http://localhost:3000",
  priceUsdc: 0.001,
  citationMultiplier: 5,
  paymentMode: "mock",
  settlementNetwork: "arcTestnet",
  tollgatePort: 8402,
  articlePrefixes: "essays,articles,posts",
  creditsPath: "./credits.json",
  starterSlug: "welcome",
  starterTitle: "Welcome",
  starterAuthorId: "you",
} as const;

export interface PlanFile {
  /** Relative to the target directory. */
  path: string;
  contents: string;
}

export interface InitPlan {
  env: PlanFile;
  credits: PlanFile;
  /** Non-fatal things the operator must know (mock mode, placeholder wallet, gateway creds). */
  warnings: string[];
  /** Printed after the files land — the "what now" a good scaffolder always ends with. */
  nextSteps: string[];
}

function renderEnv(a: InitAnswers): string {
  const gateway = a.paymentMode === "gateway";
  const lines = [
    "# naulon gate — generated by `naulon init`. Edit freely; re-run init to regenerate.",
    "# The full annotated reference is .env.example.",
    "",
    "# ── Core toll ──",
    `PAYMENT_MODE=${a.paymentMode}`,
    `# The site the gate sits in front of. A machine request to a gateable path gets tolled;`,
    `# a human request is proxied straight through, free.`,
    `ORIGIN_URL=${a.originUrl}`,
    `TOLLGATE_PORT=${a.tollgatePort}`,
    `# Comma-separated path prefixes that count as gateable articles.`,
    `ARTICLE_PATH_PREFIXES=${a.articlePrefixes}`,
    "",
    "# ── Price ──",
    `# A single read costs this much USDC. A citation costs CITATION_MULTIPLIER× a read.`,
    `DEFAULT_PRICE_USDC=${a.priceUsdc}`,
    `CITATION_MULTIPLIER=${a.citationMultiplier}`,
    "",
    "# ── Credits (who gets paid) ──",
    `# The gate reads this local JSON file to map an article slug → its author wallet(s).`,
    `# Swap to a live API instead by setting CREDITS_API_URL.`,
    `CREDITS_FIXTURES=${a.creditsPath}`,
    "",
    "# ── Settlement ──",
  ];
  if (gateway) {
    lines.push(
      `SETTLEMENT_NETWORK=${a.settlementNetwork}`,
      `# gateway mode settles real USDC. Fill these before it can settle — see .env.example:`,
      `#   RELAYER_PRIVATE_KEY=   (Arc memo self-relay; pays gas, never touches transferred funds)`,
      `#   CIRCLE_API_KEY=        (Circle Gateway; testnet facilitator needs no key)`,
      `# CREDITS_SETTLEMENT_SECRET is optional — unset keeps the earnings emit dark (still tolls).`,
    );
  } else {
    lines.push(
      `# mock mode signs payments offline — the whole loop runs with no wallet or API keys.`,
      `# Set PAYMENT_MODE=gateway (and re-run init) when you're ready to settle real USDC.`,
    );
  }
  return lines.join("\n") + "\n";
}

function buildStarterCredits(a: InitAnswers): { map: Record<string, ArticleCredits>; usedPlaceholder: boolean } {
  const usedPlaceholder = a.defaultWallet === undefined;
  const entry: ArticleCredits = {
    slug: a.starterSlug,
    title: a.starterTitle,
    contributors: [{ authorId: a.starterAuthorId, wallet: walletAddress(a.defaultWallet ?? PLACEHOLDER_WALLET) }],
  };
  // Never emit a file the gate would reject — validate through the real contract.
  parseCredits(entry, `starter credits for "${a.starterSlug}"`);
  return { map: { [a.starterSlug]: entry }, usedPlaceholder };
}

/**
 * Turn validated answers into the two files the gate boots from. Pure: no I/O, no prompts.
 * Throws only if a generated credits entry fails the contract (a guard, not an expected path).
 */
export function buildInitPlan(answers: InitAnswers): InitPlan {
  const a = initAnswersSchema.parse(answers);
  const { map, usedPlaceholder } = buildStarterCredits(a);

  const warnings: string[] = [];
  if (a.paymentMode === "mock") {
    warnings.push("PAYMENT_MODE=mock — payments are signed offline; no real USDC moves. Fine for local dev.");
  } else {
    warnings.push(
      `PAYMENT_MODE=gateway on ${a.settlementNetwork} — set RELAYER_PRIVATE_KEY / CIRCLE_API_KEY in .env before a real settle.`,
    );
  }
  if (usedPlaceholder) {
    warnings.push(
      `${a.creditsPath} uses a placeholder wallet (0x00…00). Replace it with a real address, or agents pay into the void.`,
    );
  }

  return {
    env: { path: ".env", contents: renderEnv(a) },
    credits: { path: a.creditsPath, contents: JSON.stringify(map, null, 2) + "\n" },
    warnings,
    nextSteps: [
      "Review .env and " + a.creditsPath + " — add your real article slugs + author wallets.",
      `Draft entries from your live site:  npx naulon crawl ${a.originUrl} --prefixes ${a.articlePrefixes}`,
      "Start the gate:  make dev",
      `Watch the toll:  curl -A python-requests localhost:${a.tollgatePort}/${a.articlePrefixes.split(",")[0]}/${a.starterSlug}`,
      "Health-check anytime:  npx naulon doctor",
    ],
  };
}
